apiVersion: v1
kind: Service
metadata:
  name: micro-web
  namespace: default
  labels:
    name: micro-web
    micro: runtime
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: micro-web
    micro: runtime
  type: LoadBalancer
